### ISSUE TITLE
The project cards overlap in resolutions smaller than 1750px wide

### ISSUE THREAD

**Issue by aalexmrt** [lmnr-ai/lmnr#108]
On the projects page, the project cards overlap in resolutions smaller than 1750px wide.
I’m using a MacBook Pro 16” at the default display setting and 100% browser zoom.

<img width="1728" alt="Screenshot 2024-10-29 at 09 48 35" src="https://github.com/user-attachments/assets/291c6130-e704-4bb5-a5c3-0cd7a26839fa">

**Comment by lucky29-git** [comment]
Can i work on this? @dinmukhamedm

**Comment by lucky29-git** [comment]
Thanks @aalexmrt

**Comment by dinmukhamedm** [comment]
@lucky29-git you can ping me in our [Discord server](https://discord.gg/nNFUUDAKub) in the bug-report channel. I have a couple ideas, let's take the discussion on from there.

Also, thanks @aalexmrt, would you mind sharing your experience with me too – you can do that on Discord as well? I will update the contributing guidelines or our setup accordingly!
