### ISSUE TITLE
Expandable sidebar

### ISSUE THREAD

**Issue by skull8888888** [lmnr-ai/lmnr#127]
Add expandable sidebar on hover or on click of a button. Don't know the final design yet. Open to suggestions.

**Comment by alibinauanov** [comment]
do you need firstly the design draft on figma?

**Comment by dinmukhamedm** [comment]
Hey @alibinauanov thanks for your interest. Unfortunately, somebody is already working on this in #194. Sorry that we haven't updated this issue.

There are many more features that are essentially stale (assigned, but apparently no work is being done right now). Feel free to comment under them pinging the assignee and asking if you could take the work over

**Comment by alibinauanov** [comment]
> Hey @alibinauanov thanks for your interest. Unfortunately, somebody is already working on this in #194. Sorry that we haven't updated this issue.
> 
> There are many more features that are essentially stale (assigned, but apparently no work is being done right now). Feel free to comment under them pinging the assignee and asking if you could take the work over

hey @dinmukhamedm thanks for letting me know!

**Comment by skull8888888** [comment]
solved with https://github.com/lmnr-ai/lmnr/pull/273
