### ISSUE TITLE
Replace Loader by Loader2 everywhere

### ISSUE THREAD

**Issue by skull8888888** [lmnr-ai/lmnr#128]
Replace shadcn Loader with Loader2

**Comment by lucky29-git** [comment]
Hey @skull8888888
The loader imported from shadcn should look something like @/components/ui/loader 
But I noticed all the loaders are imported from lucide-react. should I replace these?

**Comment by lucky29-git** [comment]
Hey @dinmukhamedm please have a look.

**Comment by dinmukhamedm** [comment]
Thanks @lucky29-git, merged into dev. We will merge to main later today and release on the cloud some time this weekend!

**Comment by lucky29-git** [comment]
Yeah sure 👍
