### ISSUE TITLE
Is it free to all and open source 

### ISSUE THREAD

**Issue by yedidyar-ni** [lmnr-ai/lmnr#13]
I saw that there a pricing is it only for the managed platform

Can I self host it?

**Comment by skull8888888** [comment]
Hey there, yep pricing is only for the managed platform. You absolutely can self-host with docker compose! Check out small guide in the readme of the project.

**Comment by Yedidyar** [comment]
Ok thanks
Thanks for creating this project. Your work is appreciated.🙂
