### ISSUE TITLE
Reset pageNumber to 0 when changing filters

### ISSUE THREAD

**Issue by dinmukhamedm** [lmnr-ai/lmnr#150]
This is true for any table with [manual] pagination, spans and traces are a good candidate

### Reproduction step
- Have multiple pages of traces for the last 24 hours
- Have less than one page of traces for the last 1 hour
- Set the filter to 24 hours.
- Go past page 1, e.g. page 3
- Set the filter back to 1 hour

### Expected behavior
I can see my traces for the last hour

### Actual behavior
I see an empty page, because I am in page 3/1

TODO:
Reset pageNumber to 0 when filters change. We can be smart here, e.g. do this only if filters change or if the time range _decreases_. If we merely increase the time range, it probably makes sense to stay on the same page

**Comment by sarthakvijayvargiya** [comment]
@dinmukhamedm  Hey! Could we work on this together? I’ll ask for help if I run into any issues.

**Comment by dinmukhamedm** [comment]
Sure @sarthakvijayvargiya let's work together. I gave it another thought, and I think it makes sense to control/parse the page size and page number to/from the URL params right inside the `DataTablePagination` component. Let me know if you have further questions!

**Comment by sarthakvijayvargiya** [comment]
Thanks for the guidance! I don't have any questions right now, but I’ll reach out if anything comes up.

**Comment by sarthakvijayvargiya** [comment]
Hi @dinmukhamedm to reproduce this issue, should I set up a dummy project and integrate Laminar into it, or is there another way to replicate the bug?

**Comment by dinmukhamedm** [comment]
@sarthakvijayvargiya First off when you spin up laminar locally, you will have to create a Laminar project any way. Then you have two options:
1. Send traces from a toy python/js project (no need for LLM calls, you could just `observe` your functions.
2. Seed the database with a bit of fake data. For this option you will need to 
    1. `cd frontend && npx drizzle-kit studio`
    2. go to https://local.drizzle.studio/ and in the SQL editor run some SQL to insert fake traces and spans.

I will add some SQL fake data to this comment a little bit later today, but let me know if you managed to go with option 1

**Comment by sarthakvijayvargiya** [comment]
I tried above steps - 
I have started laminar locally , created project.
1. In first options - Tried to `observe` function ,but kept getting this error 
![image](https://github.com/user-attachments/assets/38bad469-b92f-4963-aec6-91cfa0e66698)
2. 
![image](https://github.com/user-attachments/assets/04984cff-b684-493a-917f-98497a425d8d)
