### ISSUE TITLE
Ability to handle opentelemetry exceptions

### ISSUE THREAD

**Issue by Mohit21GoJs** [lmnr-ai/lmnr#179]
Hi Team,

Thanks for open sourcing this amazing tool.

I would like to know what is best way to handle exceptions caused during signoz auto instrumentation, we have a use case where sometimes tool calls fails due to signoz opentelemetry/api dependency. Sample error:

```
TypeError: Cannot read properties of null (reading 'match')\n" +
        '   at _Tiktoken.encode (/usr/src/app/node_modules/.pnpm/js-tiktoken@1.0.14/node_modules/js-tiktoken/dist/index.cjs:121:33)\n' +
        '   at OpenAIInstrumentation.tokenCountFromString (/usr/src/app/node_modules/.pnpm/@traceloop+instrumentation-openai@0.11.1_@opentelemetry+api@1.9.0/node_modules/@traceloop/src/instrumentation.ts:738:21)\n' +
        '   at OpenAIInstrumentation._streamingWrapPromise_1 (/usr/src/app/node_modules/.pnpm/@traceloop+instrumentation-openai@0.11.1_@opentelemetry+api@1.9.0/node_modules/@traceloop/src/instrumentation.ts:422:18)\n' +
        '   at _streamingWrapPromise_1.next (<anonymous>)\n' +
        '   at resume (/usr/src/app/node_modules/.pnpm/tslib@2.7.0/node_modules/tslib/tslib.js:282:48)\n' +
        '   at fulfill (/usr/src/app/node_modules/.pnpm/tslib@2.7.0/node_modules/tslib/tslib.js:284:35)\n' +
        '   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
```

This generally happens during tool call, is it possible to handle these exceptions to not fail our llm calls response and just log it somewhere?

**Comment by dinmukhamedm** [comment]
Hey @Mohit21GoJs thanks for your question. I have a guess at where this may be coming from and will work on a fix, but could you please confirm the following:
- Your version of `@lmnr-ai/lmnr`
- If you are using any `@traceloop` packages directly for your instrumentation
- If you can provide a small snippet or gist to reproduce this, it would be greatly helpful

**Comment by Mohit21GoJs** [comment]
@dinmukhamedm Thanks for the response, here are answers for questions:

1. @lmnr-ai/lmnr@0.4.14

2. We use auto instrumentation of node as suggested here with SigNoz: https://signoz.io/docs/instrumentation/opentelemetry-nestjs/#using-a-specific-auto-instrumentation-library

3. I can share how i am calling the function
https://gist.github.com/Mohit21GoJs/8e0dde3deccb4af1515e70f578fb7ec5

I would assume in case of failure to generate trace this should not impact my api and i would like to handle such runtime errors to not break our api as it would cause production issues, and hence would be good to know proactiv approach to handle these issues, thanks in advance.

**Comment by dinmukhamedm** [comment]
Yes, I understand that this is truly disappointing and your calls must not fail because of failures in the instrumentation. Sorry about that.

This, I am pretty sure, to do with how underlying auto-instrumentation counts tokens. Can you please try and upgrade to `v0.4.19`? Please let me know if this fixes the issue.

I think this is to do with how OpenLLMetry handles token counting, which I explicitly disable since v0.4.19. However, I was not able to reproduce... So @Mohit21GoJs  please let me know if the update fixes it.

Also, I am closing #28 in favour of this one

**Comment by Mohit21GoJs** [comment]
@dinmukhamedm Thanks a lot for the quick fix, i will be testing it out today after upgrading to 0.4.19 and will update here, thanks again 🫡

**Comment by dinmukhamedm** [comment]
@Mohit21GoJs did the update resolve your issue?

**Comment by Mohit21GoJs** [comment]
Hi @dinmukhamedm Yes we are not facing the above error now, thanks a lot :)
