### ISSUE TITLE
Enable download in both formats: CSV and JSON

### ISSUE THREAD

**Issue by dinmukhamedm** [lmnr-ai/lmnr#268]
For historic reasons we allow downloading evaluation results in CSV and datasets in JSON. There is no reason to disallow the other format, so we should allow _both_ CSV and JSON in _both_ places.

UI: I would like to make the download button a dropdown, so that when you click "Donwload" there are buttons that appear under it: "Download CSV" and "Download JSON", somewhat like Supabase's "Export button".

![Screenshot 2024-12-05 at 17 32 11](https://github.com/user-attachments/assets/edc4ecf0-8c52-46c6-a4e9-0b3b6b2f164b)

Pointers:
- Bare JSON download in dataset: https://github.com/lmnr-ai/lmnr/blob/main/frontend/app/api/projects/%5BprojectId%5D/datasets/%5BdatasetId%5D/download/route.ts
- CSV conversion before download in https://github.com/lmnr-ai/lmnr/blob/main/frontend/app/api/projects/%5BprojectId%5D/evaluations/%5BevaluationId%5D/download/route.ts#L69-L72

**Comment by devansh-m12** [comment]
I'd like to work on this issue. Could you please assign it to me?

**Comment by dinmukhamedm** [comment]
Addressed in #272
