### ISSUE TITLE
Add CTA to reset filters if filters are applied and 0 results are shown

### ISSUE THREAD

**Issue by dinmukhamedm** [lmnr-ai/lmnr#269]
Any page with `DatatableFilter` is sometimes misleadingly empty when filters are applied – i.e. it is easy to accidentally forget that filters are applied.

Add some kind of a `Card` right in the middle of the page with a call to action to disable filters to see all results. The text could be something like

"Applied filters returned no results. <Button> Clear filters </Button>".

This will probably involve editing either the `DataTable` component or pages that use it

**Comment by devansh-m12** [comment]
something similar to this ? @dinmukhamedm 

<img width="1710" alt="Screenshot 2024-12-06 at 8 27 56 AM" src="https://github.com/user-attachments/assets/fecee863-42b1-4c21-bc3d-34d03991f3d7">

**Comment by dinmukhamedm** [comment]
@devansh-m12 that looks good! Could you please change the color on "Clear filters" part to `className="text-primary"`?

**Comment by dinmukhamedm** [comment]
Closed via #270
