### ISSUE TITLE
Add "items count" column to the list of datasets

### ISSUE THREAD

**Issue by skull8888888** [lmnr-ai/lmnr#274]
Add "items count" column to the list of datasets which would simply show how many datapoints given dataset has.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change adds an 'Items count' column to the list of datasets, showing the number of datapoints for each dataset. Changes include updating the backend API to include the count, modifying the frontend to display the new column, and ensuring proper styling and functionality.

You can review changes in this commit: https://github.com/mnmnk43434/lmnr-ai-lmnr-274/commit/4467220c19c04335d22c64205659a135ff267082.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by devansh-m12** [comment]
I would like to work on this issue can you assign this to me
