### ISSUE TITLE
Asyncio version is too old to deploy on AWS

### ISSUE THREAD

**Issue by tinghao-ai** [lmnr-ai/lmnr#29]
When add lmnr for my fastapi project deploy to AWS, this error happens:

`Error type: Runtime.UserCodeSyntaxError
Error location: In module 'main', file base_events.py, line 296
Error code:
pythonCopyfuture = tasks.async(future, loop=self)

Error reason: 'async' is a reserved keyword in Python and cannot be used as a function or method name.
Occurrence time: The error occurred repeatedly from 2024-10-10T05:00:36 to 2024-10-10T05:00:49
Impact: The initialization and call phases of the Lambda function failed and could not be executed normally`

**Comment by dinmukhamedm** [comment]
Hey, thanks for flagging. We do indeed depend on [asyncio in Python](https://github.com/lmnr-ai/lmnr-python/blob/main/pyproject.toml#L26) explicitly, which apparently isn't right for any Python 3.4+.

> This version is only relevant for Python 3.3, which does not include asyncio in its stdlib.

[link](https://pypi.org/project/asyncio/#description)

I'll release a new version pretty soon, but for more context, could you add a bit more information which dependency manager and OS you use? E.g. pip + ubuntu

**Comment by dinmukhamedm** [comment]
Merged and published v`0.4.21`. Could you try `pip install --upgrade lmnr`? Let us know, if the problem persists, and feel free to close this issue otherwise
