### ISSUE TITLE
The sign-in page is still using the old logo

### ISSUE THREAD

**Issue by aalexmrt** [lmnr-ai/lmnr#87]
Do you want to keep the old logo on this page? @skull8888888

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/984d63e7-dd17-4236-946e-aafe4fc5f48f">

**Comment by skull8888888** [comment]
@aalexmrt totally missed that, thank you, gonna ship quick fix!

**Comment by skull8888888** [comment]
done
